changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Exciting New Features
      labels:
        - enhancement
    - title: Exciting New Features
      labels: Bug Fixes
        - bug-fix
    - title: Other Changes
      labels:
        - "*"
