
name: Build Tool on Windows & Linux

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Create a Directory for Windows Artifact
      run: mkdir Build_Windows
    - name: Build
      run: cd Build_Windows && pwd && cmake .,
    - name: Make
      run: cmake --build .

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Create a Directory for Linux Artifact
      run: mkdir Build_Linux
    - name: Build
      run: cd Build_Linux && pwd && cmake ..
    - name: Make
      run: make
