
name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: pwd && cmake .
    - name: Make
      run: cmake --build .

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: pwd && cmake .
    - name: Make
      run: make
