# Name of the Testing Workflow
name: Linux Build

# Events at which this workflow is executed
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Actual Workflow Scripts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: sudo apt-get install libgtest-dev
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake
    - name: Make
      run: cd build && make
