# Name of the Testing Workflow
name: Linux Build

# Events at which this workflow is executed
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Actual Workflow Scripts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install dependencies
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
    # Build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
