# Name of the Testing Workflow
name: Linux Build

# Events at which this workflow is executed
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Actual Workflow Scripts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: pwd && cmake .
    - name: Make
      run: make
