
name: Codebase Documentation

on:
  workflow_call

jobs:

  clang-format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Check Codebase Format
      uses: RafikFarhad/clang-format-github-action@v1.0.1
      with:
        sources: "src/*.cpp,include/*.h,test/*.cpp"
