name: Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
        
permissions:
  deployments: write
  contents: write

jobs:

  codebase:
    name: Codebase
    uses: Shehab7osny/DiffCpp/.github/workflows/codebase.yml@main
        
  build:
    name: Build
    uses: Shehab7osny/DiffCpp/.github/workflows/build.yml@main

  verification:
    name: Testing
    needs:
      - build
    uses: Shehab7osny/DiffCpp/.github/workflows/testing.yml@main
