name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: pwd && cmake .
    - name: Make
      run: cmake --build .

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: pwd && cmake .
    - name: Make
      run: make

  clang-format-check:
    name: Clean Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    # - name: Check Codebase Format
    #   uses: HorstBaerbel/action-clang-format@1.5

  release:
    name: Unit Tests
    needs:
      - build-windows
      - build-linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache GoogleTest Package
      id: cached-gtest
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-repo
      with:
        path: googletest
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install GoogleTest
      if: steps.cached-gtest.outputs.cache-hit != 'true'
      run: mkdir googletest &&
           git clone https://github.com/google/googletest.git googletest

    - name: Build
      run: cmake -DBUILD_TESTS=ON .

    - name: Make
      run: make
      
    - name: Run Unit Tests
      run: ./DiffCpp_tst
