name: Testing

on:
  workflow_call

jobs:

  verification:
    name: Unit and Block
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache GoogleTest Package
      id: cached-gtest
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-repo
      with:
        path: googletest
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install GoogleTest
      if: steps.cached-gtest.outputs.cache-hit != 'true'
      run: mkdir googletest &&
           git clone https://github.com/google/googletest.git

    - name: Build
      run: cmake -DBUILD_TESTS=ON .

    - name: Make
      run: make
      
    - name: Run Unit Tests
      run: ./DiffCpp_tst
