name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache GoogleTest package
      id: cached-gtest
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-package
      with:
        path: /home/runner/work/DiffCpp/DiffCpp
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Clone GoogleTest repository
      # if: steps.cached-gtest.outputs.cache-hit != 'true'
      run: sudo apt-get install libgtest-dev &&
           cd /usr/src/gtest &&
           sudo cmake CMakeLists.txt &&
           sudo make &&
           sudo cp *.a /usr/lib &&
           sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a &&
           sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Build gtest
      run: cmake .

    - name: Make
      run: make
      
    - name: Run Test
      run: ls && pwd
