name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      run: mkdir /home/runner/work/DiffCpp/DiffCpp/lib 
           && cd /home/runner/work/DiffCpp/DiffCpp/lib 
           && git clone https://github.com/google/googletest/ 
           && ls 
           && ls /home/runner/work/DiffCpp/DiffCpp/lib/
           && cmake .
           && make
           && /home/runner/work/DiffCpp/DiffCpp/DiffCpp_tst
    - uses: actions/checkout@v1
