name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache GoogleTest package
      id: cached-gtest
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-package
      with:
        path: .
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Clone GoogleTest repository
      if: steps.cached-gtest.outputs.cache-hit != 'true'
      run: git clone https://github.com/google/googletest/

    - name: Build
      run: cmake .

    - name: Make
      run: make
      
    - name: Run Test
      run: ls
