name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest
      run: mkdir /home/runner/work/DiffCpp/DiffCpp/lib 
           && cd /home/runner/work/DiffCpp/DiffCpp/lib 
           && git clone https://github.com/google/googletest/ 
    - name: Build
      run: cmake .
    - name: Make
      run: make
