name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache GoogleTest package
      id: cached-gtest
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-package
      with:
        path: ./googleTest
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install GoogleTest
      # if: steps.cached-gtest.outputs.cache-hit != 'true'
      run: sudo apt-get install libgtest-dev &&
           cp -r /usr/src/gtest . &&
           cd gtest && ls &&
           sudo cmake CMakeLists.txt &&
           sudo make

    - name: Check cached directory
      run: cd ./googleTest && ls

    - name: Build
      run: cmake -DBUILD_TESTS=ON .

    - name: Make
      run: make
      
    - name: Run Test
      run: ./DiffCpp_tst
