name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache GoogleTest package
      id: cached-gtest
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-package-new1
      with:
        path: sudo /usr/src/gtest/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install GoogleTest package
      if: steps.cached-gtest.outputs.cache-hit != 'true'
      run: sudo apt-get install libgtest-dev

    - name: Check cached data
      run: cd /usr/src/gtest/ &&
           ls

    - name: Build Try
      run: cmake -DBUILD_TESTS=ON .

    - name: Make
      run: make
      
    - name: Run Test
      run: ./DiffCpp_tst
